repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--line-length=119"]

      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        files: '\.(py|ipynb)$'
        types_or: [python, jupyter]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]

      - id: nbqa
        name: nbqa
        entry: nbqa black
        language: system
        files: \.ipynb$
        